version: 2.1
jobs:
  build:
    docker:
      - image: ocaml/opam2:4.09
        environment:
          PGUSER: pgx
          PGDATABASE: pgx-test
          PGHOST: 127.0.0.1
          PGX_FORCE_TESTS: true
          TERM: xterm
      - image: circleci/postgres:9.6-alpine
        environment:
          POSTGRES_USER: pgx
          POSTGRES_DB: pgx-test
          POSTGRES_PASSWORD: ""
    steps:
      - checkout
      - run:
          name: Update opam
          command: |
            opam remote remove default --all
            opam remote add default https://opam.ocaml.org
      - run:
          name: Pin packages
          command: |
            for p in *.opam; do
              opam pin add -k git -y -n ${p%.opam} .
            done
      - run:
          name: Install system dependencies
          command: opam depext -y `basename -s .opam *.opam | tr '\n' ' '`
      - run:
          name: Install OCaml dependencies
          command: opam install --deps-only -y `basename -s .opam *.opam | tr '\n' ' '`
      - run:
          # This is a separate step so we don't run tests for all of these ^
          name: Install OCaml test dependencies
          command: opam install --deps-only -t -y `basename -s .opam *.opam | tr '\n' ' '`
      - run:
          name: Build
          command: opam config exec -- make
      - run:
          name: Test and coverage report
          command: |
            opam config exec -- make coverage

  # This build step ensures we can build a mirage unikernel but doesn't make any attempt to run it
  # We're basically just trying to ensure our build deps are ok
  build_mirage:
    docker:
      - image: ocaml/opam2:4.09
        environment:
          TERM: xterm
    steps:
      - checkout
      - run:
          name: Update opam
          command: |
            opam remote remove default --all
            opam remote add default https://opam.ocaml.org
      - run:
          name: Pin packages
          command: opam pin add -k git -y -n pgx .
      - run:
          name: Install system dependencies
          command: opam depext -y pgx
      - run:
          name: Install OCaml dependencies
          command: opam install --deps-only -y pgx
      - run:
          name: Install mirage
          command: opam install -y mirage
      - run:
          name: Configure mirage
          command: cd mirage && opam exec -- mirage configure -t spt
      - run:
          name: Install mirage deps
          command: cd mirage && opam exec -- make depend
      - run:
          name: Build mirage
          command: cd mirage && opam exec -- make

workflows:
  main:
    jobs:
      - build
      - build_mirage
